import { boolean, index, integer, pgTable, primaryKey, real, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

// ── Auth (tables and columns as Better Auth expects them) ──────────────────

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  // When the reader asked for the newsletter (NEWSLETTER=true servers); null =
  // not subscribed. Kept as a time, so the operator can show when they agreed.
  newsletterConsentAt: timestamp("newsletter_consent_at"),
  // When the account last signed in or used Bookplate, to the day (see
  // markSeen in lib/auth.ts) — for finding long-unused accounts.
  lastSeenAt: timestamp("last_seen_at").notNull().defaultNow(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (t) => [index("session_user_idx").on(t.userId)]
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [index("account_user_idx").on(t.userId)]
);

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

// Failed-password counting per account (see lib/authThrottle.ts).
export const authThrottle = pgTable("auth_throttle", {
  key: text("key").primaryKey(), // e.g. "sign-in:reader@example.com"
  failures: integer("failures").notNull(),
  windowStart: timestamp("window_start").notNull(),
});

// ── Library ────────────────────────────────────────────────────────────────
// Every row belongs to a user. Ids are generated by the client (UUIDs, or
// older "seed-…" ids from imported libraries), so they are only unique per
// user: two accounts importing the same export must not collide.

export const book = pgTable(
  "book",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    id: text("id").notNull(),
    title: text("title").notNull(),
    author: text("author").notNull(),
    isbn: text("isbn"), // ISBN-13 or ISBN-10, digits only (plus a trailing X)
    olWorkId: text("ol_work_id"), // Open Library work, e.g. OL893415W (books added from the catalogue)
    genre: text("genre"),
    pages: integer("pages"),
    format: text("format"),
    status: text("status").notNull(),
    copy: boolean("copy"),
    rating: real("rating").notNull().default(0),
    dateRead: text("date_read"), // ISO yyyy-mm-dd, kept as text like the app uses it
    shortNotes: text("short_notes"), // legacy one-line notes from before notes pages
    coverImage: text("cover_image"),
    colorIndex: integer("color_index").notNull().default(0),
    addedAt: text("added_at").notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })]
);

export const note = pgTable(
  "note",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    bookId: text("book_id").notNull(),
    markdown: text("markdown").notNull(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.bookId] })]
);

// Reading progress: one entry per book per day (a second update on the same
// day replaces it). The percentage is always stored; the page too when the
// book has a page count. The first entry marks when the book was started.
export const readingProgress = pgTable(
  "reading_progress",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    bookId: text("book_id").notNull(),
    date: text("date").notNull(), // ISO yyyy-mm-dd, the reader's local date
    page: integer("page"),
    percent: real("percent").notNull(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.bookId, t.date] })]
);

export const vocabEntry = pgTable(
  "vocab_entry",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    id: text("id").notNull(),
    word: text("word").notNull(),
    phonetic: text("phonetic"),
    partOfSpeech: text("part_of_speech"),
    definition: text("definition").notNull(),
    example: text("example"),
    synonyms: text("synonyms").array(),
    bookId: text("book_id"),
    addedAt: text("added_at").notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.id] })]
);

// A public page of one year's reading (lib/showcase.ts), at /s/<id>. It holds
// only the reader's choices; the books are read live each time it's opened.
// The id is the whole address, so it's long and random, and never logged.
export const showcase = pgTable(
  "showcase",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    year: integer("year").notNull(),
    include: text("include").notNull(), // "read" | "reading" | "both"
    name: text("name"), // shown on the page; null = no name
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [uniqueIndex("showcase_user_year_idx").on(t.userId, t.year)]
);
